version: '2'


services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./code:/code
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
networks:
    code-network:
        driver: bridge
